START_OF_TEMPLATE = '<DECLARATION>'
END_OF_TEMPLATE = '</DECLARATION>'
START_OF_VAR = '<VAR>'
END_OF_VAR = '</VAR>'
START_OF_PARAM = '<PARAM>'
END_OF_PARAM = '</PARAM>'
START_OF_LIMIT= '<LIMIT>'
END_OF_LIMIT = '</LIMIT>'
START_OF_OBJ_DIR = '<OBJ_DIR>'
END_OF_OBJ_DIR = '</OBJ_DIR>'
START_OF_OBJ_NAME = '<OBJ_NAME>'
END_OF_OBJ_NAME = '</OBJ_NAME>'
START_OF_CONST_DIR = '<CONST_DIR>'
END_OF_CONST_DIR = '</CONST_DIR>'
START_OF_CONST_TYPE = '<CONST_TYPE>'
END_OF_CONST_TYPE = '</CONST_TYPE>'
START_OF_OPERATOR = '<OPERATOR>'
END_OF_OPERATOR = '</OPERATOR>'

IS_TOKEN = '[is]'
TIMES_TOKEN = '[times]'
PLUS_TOKEN = '[plus]'
FOR_TOKEN = '[for]'

ONE_TOKEN = 'ONE'

TYPE_UPPER_BOUND = "[UPPER_BOUND]"
TYPE_LOWER_BOUND = "[LOWER_BOUND]"
TYPE_SUM_CONST = "[SUM_CONSTRAINT]"
TYPE_LINEAR_CONST = "[LINEAR_CONSTRAINT]"
TYPE_RATIO_CONST = "[RATIO_CONSTRAINT]"
TYPE_XBY_CONST = "[XBY_CONSTRAINT]"
TYPE_XY_CONST = "[XY_CONSTRAINT]"

SPECIAL_TOKENS = [
    START_OF_TEMPLATE, END_OF_TEMPLATE,
    START_OF_VAR, END_OF_VAR,
    START_OF_LIMIT, END_OF_LIMIT,
    START_OF_OBJ_DIR, END_OF_OBJ_DIR,
    START_OF_CONST_DIR, END_OF_CONST_DIR,
    START_OF_CONST_TYPE, END_OF_CONST_TYPE,
    START_OF_OPERATOR, END_OF_OPERATOR,
    IS_TOKEN,
    TIMES_TOKEN,
    PLUS_TOKEN,
    FOR_TOKEN,
    TYPE_UPPER_BOUND,
    TYPE_LOWER_BOUND,
    TYPE_SUM_CONST,
    TYPE_LINEAR_CONST,
    TYPE_RATIO_CONST,
    TYPE_XBY_CONST,
    TYPE_XY_CONST,
    ONE_TOKEN
]




